# Declare services.
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: .
    restart: on-failure:10
    volumes:
      - ./:/workspace
      - /workspace/node_modules
      - /workspace/.next
    ports:
      - '3000:3000'
      - '6006:6006'
