import Head from 'next/head';
import type { NextPage } from 'next';
import { PageQuery } from 'src/backend/queries/page';
import { CustomPortableText } from '@components/custom-portable-text';
import useSWR from 'swr';
import { client } from 'src/backend/client';
import { ISanityPage } from 'src/backend/types/entities/page';
import { customPortableTextRaw } from '@components/cards/card/mock-data';
import Container from '@components/container';

const Home: NextPage = () => {
  const { data, error, isLoading } = useSWR<ISanityPage>(PageQuery, (query) =>
    client.fetch(query)
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center flex-1 min-h-screen bg-gray-light dark:bg-black">
        <section className="section-padding-primary">
          <Container>
            {isLoading && <div>Loading...</div>}
            {error && <div>{error.message}</div>}
            {data && <CustomPortableText content={customPortableTextRaw} />}
          </Container>
        </section>
      </main>
    </>
  );
};

export default Home;
