import Head from 'next/head';
import type { NextPage } from 'next';
import { PageQuery } from 'src/backend/queries/page';
import { CustomPortableText } from '@components/custom-portable-text';
import useSWR from 'swr';
import { client } from 'src/backend/client';
import { ISanityPage } from 'src/backend/types/entities/page';

const Home: NextPage = () => {
  const { data, error, isLoading } = useSWR<ISanityPage>(PageQuery, (query) =>
    client.fetch(query)
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-1 flex-col justify-center items-center min-h-screen pt-16 bg-slate-100 dark:bg-slate-800">
        {isLoading && <div>Loading...</div>}
        {error && <div>{error.message}</div>}
        {data && (
          <div>
            <CustomPortableText content={data.content} />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
