import type { NextPage } from 'next';
import Head from 'next/head';
// import ExampleBody from 'src/sections/body/example';
// import ExampleFooter from 'src/layout/footer/example';
// import ExampleHero from 'src/sections/hero/example';
import Carousel from '@components/swiper';
import {
  swiperCommonOptions,
  swiperPreviewimages,
} from '@components/swiper/mock-data';
import { SwiperSlide } from 'swiper/react';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Template Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ExampleHero
        title={{
          regularPart: 'NextJS Template',
          emphasizedPart: 'Draft One',
        }}
        description={
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
        }
      />
      <ExampleBody content="This is a body section" />
      <ExampleFooter /> */}

      <Slider />
      <Slider />
      <Slider />
      <Slider />
      <Slider />
    </>
  );
};

export default Home;

const Slider = () => {
  return (
    <div className="section-padding-primary">
      <Carousel {...swiperCommonOptions} haveOffset>
        {swiperPreviewimages.map((swiperPreviewimage, index) => (
          <SwiperSlide key={index}>
            <Image
              src={`${swiperPreviewimage}`}
              alt={`image-${index}`}
              width={960}
              height={720}
            />
          </SwiperSlide>
        ))}
      </Carousel>
    </div>
  );
};
