import type { NextPage } from 'next';
import Head from 'next/head';
import ExampleBody from 'src/sections/body/example';
import ExampleFooter from 'src/sections/footer/example';
import ExampleHero from 'src/sections/hero/example';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Template Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ExampleHero
        title={{
          regularPart: 'NextJS Template',
          emphasizedPart: 'Draft One',
        }}
        description={
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
        }
      />
      <ExampleBody content="This is a body section" />
      <ExampleFooter />
    </>
  );
};

export default Home;
